### ISSUE TITLE
Allow \uXXXX to specify unicode symbols

### ISSUE THREAD

**Issue by Krakean** [salaros/config-parser#13]
Suggestion to add support for \uXXXX form (should be valid unicode scalar value) as the way to specify unicode symbols
For example:
[Temp]
name = "Windows"
name.company = "Microsoft \u00A9"

Because if we currently will try to write like this:
[Temp]
name = "Windows"
name.company = "Microsoft ©"

We will get this message:
 = No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
  Data = <enumerable Count: 0>
  HelpLink = <null>
  HResult = -2146233067
  InnerException = <null>
  Message = No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
  Source = System.Private.CoreLib
  StackTrace =    at System.Text.Encoding.GetEncoding(Int32 codepage)
   at System.IO.FileInfoExtensions.IsInAnsiLatin1(FileInfo file, Double mangledCharThreshold)
   at System.IO.FileInfoExtensions.TryGetEncoding(FileInfo file, Encoding& encoding)
   at System.IO.FileInfoExtensions.GetEncoding(FileInfo file, Boolean throwIfNotDetected)
   at Salaros.Configuration.ConfigParser..ctor(String configFile, ConfigParserSettings settings)

**Comment by salaros** [comment]
I think you just have to set a non ANSI file encoding, such as UTF7, UTF8, UTF16, UTF32 etc, otherwise you won't be able to use Unicode symbols at all.

```csharp
var tempConfigFilePath = Path.GetTempFileName();
var configParser = new ConfigParser(
   tempConfigFilePath,
   new ConfigParserSettings
   {
	   MultiLineValues = MultiLineValues.QuoteDelimitedValues,
	   KeyValueSeparator = " = ",
	   Encoding = new UTF8Encoding(false, false)
   }
);

configParser.SetValue("Temp", "name", "Windows");
configParser.SetValue("Temp", "name.company", "Microsoft \u00A9");
```

I've just added [a test](https://github.com/salaros/config-parser/blob/master/tests/ConfigParserTests.cs#L690) for this functionality here.

**Comment by salaros** [comment]
Please consider starring this repo if you like it and you think it deserves more attention
