### ISSUE TITLE
Add support for underscores between digits to enhance redability

### ISSUE THREAD

**Issue by Krakean** [salaros/config-parser#14]
Each underscore must be surrounded by at least one digit on each side.
Like:
[Temp]
name.int = 1_234_567
name.int2 = 1_000
double=224_617.445_991_228

Output:
1234567
1000

**Comment by salaros** [comment]
You could already set custom [NumberFormatInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=netcore-2.2) by changing [ConfigParserSettings](https://github.com/salaros/config-parser/blob/master/src/ConfigParserSettings.cs)'s [Culture property](https://github.com/salaros/config-parser/blob/master/src/ConfigParserSettings.cs#L29).

However I made it easier to use a custom NumberFormatInfo by adding it as a parameter.
```csharp
configParser.SetValue("FormatNumber", "test.int", "1_234_567");
configParser.SetValue("FormatNumber", "test.int2", "1_000");
configParser.SetValue("FormatNumber", "double", "991_228_224_617.445");

var numberFormatInfo = new NumberFormatInfo {
	NumberGroupSeparator = "_",
	NumberDecimalSeparator = ".",
	CurrencyDecimalSeparator = "."
};
var testInt1 = configParser.GetValue("FormatNumber", "test.int", 0, NumberStyles.Integer, numberFormatInfo);
var testInt2 = configParser.GetValue("FormatNumber", "test.int2", 0, NumberStyles.Integer, numberFormatInfo);
var testDouble = configParser.GetValue("FormatNumber", "double", 0D, NumberStyles.Currency, numberFormatInfo);
```

You can see it in a [new test case](https://github.com/salaros/config-parser/blob/master/tests/ConfigParserTests.cs#L722) I've just created.

However there is a limitation: group separator, whether it's _ or , it's not allowed in the second part of the float/double/decimal number. So `991_228_224_617.445` is correct, while `123,617.445,000` and `341_227,643_000` are not!

**Comment by salaros** [comment]
Please consider starring this repo if you like it and you think it deserves more attention
