### ISSUE TITLE
Incorrect result of SetValue method

### ISSUE THREAD

**Issue by KarolPiechoczek** [salaros/config-parser#15]
For example structure of my own config file:
```
[Settings]
Recno = chocolate
```

When I use SetValue and Save methods:

```
configFileFromPath.SetValue("Settings", "Recno", "123");
configFileFromPath.Save(@".\\config.ini");
```

...my config file look like that...

```
[Settings]
Recno = 123colate
```
...instead:

```
[Settings]
Recno = 123
```

**Comment by salaros** [comment]
Hi @KarolPiechoczek,

You are right, this was a regression caused by one of my recent attempt to optimize file operations. That you very much for catching this bug.
Now there is a unit test covering your case :D https://github.com/salaros/config-parser/blob/master/tests/ConfigParserTests.cs#L9

**Comment by salaros** [comment]
Try updating to version 0.3.4 and don't forget to start this project if you like it.
Have a nice day

**Comment by KarolPiechoczek** [comment]
Hello, thank a lot, now everything work.
