### ISSUE TITLE
Redis config value can either be "xxx" or xxx, the double quotation should ignore when parsing

### ISSUE THREAD

**Issue by naughtyGitCat** [salaros/config-parser#21]
`YAML` also has this feature, the quote on string value is not mandatory.

```ini
x="a"
y=b
```
should be cast to 
```
X = a
Y = b
```
not 
```
X = "a"
Y = b
```

**Comment by salaros** [comment]
> 
> 
> `YAML` also has this feature, the quote on string value is not mandatory.
> 
> ```ini
> x="a"
> y=b
> ```
> 
> should be cast to
> 
> ```
> X = a
> Y = b
> ```
> 
> not
> 
> ```
> X = "a"
> Y = b
> ```

Have you tried using `new ConfigParser(new ConfigParserSettings { MultiLineValues = MultiLineValues.QuoteDelimitedValues })`?

**Comment by naughtyGitCat** [comment]
thanks, i will try it
